# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 05:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brokenroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('kerusakan', models.CharField(choices=[('Rusak Ringan', 'Rusak Ringan'), ('Rusak Sedang', 'Rusak Sedang'), ('Rusak Berat', 'Rusak Berat'), ('Rusak Total', 'Rusak Total')], default='Rusak Ringan', max_length=20)),
                ('traffic', models.CharField(choices=[('Sepi', 'Sepi'), ('Sedang', 'Sedang'), ('Ramai', 'Ramai'), ('Sibuk', 'Sibuk')], default='Sedang', max_length=20)),
                ('tingkat', models.CharField(choices=[('Jalan Nasional', 'Jalan Nasional'), ('Jalan Provinsi', 'Jalan Provinsi'), ('Jalan Kabupaten', 'Jalan Kabupaten'), ('Jalan Kota', 'Jalan Kota'), ('Jalan Desa', 'Jalan Desa')], default='Jalan Kabupaten', max_length=20)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Broken Roads',
            },
        ),
    ]
