# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 10:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0002_brokenroad_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa', models.CharField(max_length=40)),
                ('kode', models.CharField(max_length=9)),
                ('kecamatan', models.CharField(max_length=18)),
                ('kabupaten', models.CharField(max_length=14)),
                ('propinsi', models.CharField(max_length=9)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='brokenroad',
            name='gambar',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
