# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0003_auto_20180411_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenroad',
            name='tingkat',
        ),
        migrations.RemoveField(
            model_name='brokenroad',
            name='traffic',
        ),
        migrations.AddField(
            model_name='brokenroad',
            name='desa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desas', to='brokenroad.Desa'),
        ),
        migrations.AddField(
            model_name='brokenroad',
            name='kecamatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecamatans', to='brokenroad.Desa'),
        ),
    ]
