# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0004_auto_20180415_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desa',
            options={'ordering': ['desa']},
        ),
        migrations.RemoveField(
            model_name='brokenroad',
            name='kecamatan',
        ),
        migrations.AlterField(
            model_name='brokenroad',
            name='desa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokenroad.Desa'),
        ),
    ]
