# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0005_auto_20180416_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenroad',
            name='deskripsi',
            field=models.TextField(default='Tidak ada deskripsi', max_length=500),
        ),
    ]
