# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0007_auto_20180417_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desa',
            options={'ordering': ('brokencount',)},
        ),
        migrations.AddField(
            model_name='desa',
            name='brokencount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brokenroad',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
