# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0008_auto_20180417_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desa',
            options={'ordering': ('desa',)},
        ),
        migrations.RemoveField(
            model_name='desa',
            name='brokencount',
        ),
    ]
