# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0009_auto_20180417_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenroad',
            name='status',
            field=models.CharField(choices=[('b', 'Belum Diperbaiki'), ('s', 'Sudah Diperbaiki')], default='b', max_length=1),
        ),
    ]
