# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokenroad', '0010_brokenroad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desa',
            name='kode',
        ),
    ]
